/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedRoadmapRouteImport } from './routes/_authenticated/roadmap'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated/dashboard'
import { Route as AuthenticatedIntakeIndexRouteImport } from './routes/_authenticated/intake.index'
import { Route as ApiPublicDevLoginRouteImport } from './routes/api/public/dev-login'
import { Route as ApiProvisionCustomerRouteImport } from './routes/api/provision/customer'
import { Route as ApiPaymentWebhookRouteImport } from './routes/api/payment/webhook'
import { Route as ApiOrderCreateRouteImport } from './routes/api/order/create'
import { Route as ApiDidCheckRouteImport } from './routes/api/did/check'
import { Route as AuthenticatedIntakeNewRouteImport } from './routes/_authenticated/intake.new'
import { Route as AuthenticatedIntakeIdRouteImport } from './routes/_authenticated/intake.$id'
import { Route as AuthenticatedDashboardSteekproefRouteImport } from './routes/_authenticated/dashboard.steekproef'
import { Route as AuthenticatedDashboardKwaliteitRouteImport } from './routes/_authenticated/dashboard.kwaliteit'
import { Route as AuthenticatedDashboardAdviseurRouteImport } from './routes/_authenticated/dashboard.adviseur'
import { Route as AuthenticatedAdminRlsTestsRouteImport } from './routes/_authenticated/admin.rls-tests'

const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRoadmapRoute = AuthenticatedRoadmapRouteImport.update({
  id: '/roadmap',
  path: '/roadmap',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedIntakeIndexRoute =
  AuthenticatedIntakeIndexRouteImport.update({
    id: '/intake/',
    path: '/intake/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const ApiPublicDevLoginRoute = ApiPublicDevLoginRouteImport.update({
  id: '/api/public/dev-login',
  path: '/api/public/dev-login',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiProvisionCustomerRoute = ApiProvisionCustomerRouteImport.update({
  id: '/api/provision/customer',
  path: '/api/provision/customer',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPaymentWebhookRoute = ApiPaymentWebhookRouteImport.update({
  id: '/api/payment/webhook',
  path: '/api/payment/webhook',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiOrderCreateRoute = ApiOrderCreateRouteImport.update({
  id: '/api/order/create',
  path: '/api/order/create',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiDidCheckRoute = ApiDidCheckRouteImport.update({
  id: '/api/did/check',
  path: '/api/did/check',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedIntakeNewRoute = AuthenticatedIntakeNewRouteImport.update({
  id: '/intake/new',
  path: '/intake/new',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedIntakeIdRoute = AuthenticatedIntakeIdRouteImport.update({
  id: '/intake/$id',
  path: '/intake/$id',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedDashboardSteekproefRoute =
  AuthenticatedDashboardSteekproefRouteImport.update({
    id: '/steekproef',
    path: '/steekproef',
    getParentRoute: () => AuthenticatedDashboardRoute,
  } as any)
const AuthenticatedDashboardKwaliteitRoute =
  AuthenticatedDashboardKwaliteitRouteImport.update({
    id: '/kwaliteit',
    path: '/kwaliteit',
    getParentRoute: () => AuthenticatedDashboardRoute,
  } as any)
const AuthenticatedDashboardAdviseurRoute =
  AuthenticatedDashboardAdviseurRouteImport.update({
    id: '/adviseur',
    path: '/adviseur',
    getParentRoute: () => AuthenticatedDashboardRoute,
  } as any)
const AuthenticatedAdminRlsTestsRoute =
  AuthenticatedAdminRlsTestsRouteImport.update({
    id: '/admin/rls-tests',
    path: '/admin/rls-tests',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/dashboard': typeof AuthenticatedDashboardRouteWithChildren
  '/roadmap': typeof AuthenticatedRoadmapRoute
  '/admin/rls-tests': typeof AuthenticatedAdminRlsTestsRoute
  '/dashboard/adviseur': typeof AuthenticatedDashboardAdviseurRoute
  '/dashboard/kwaliteit': typeof AuthenticatedDashboardKwaliteitRoute
  '/dashboard/steekproef': typeof AuthenticatedDashboardSteekproefRoute
  '/intake/$id': typeof AuthenticatedIntakeIdRoute
  '/intake/new': typeof AuthenticatedIntakeNewRoute
  '/api/did/check': typeof ApiDidCheckRoute
  '/api/order/create': typeof ApiOrderCreateRoute
  '/api/payment/webhook': typeof ApiPaymentWebhookRoute
  '/api/provision/customer': typeof ApiProvisionCustomerRoute
  '/api/public/dev-login': typeof ApiPublicDevLoginRoute
  '/intake/': typeof AuthenticatedIntakeIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/dashboard': typeof AuthenticatedDashboardRouteWithChildren
  '/roadmap': typeof AuthenticatedRoadmapRoute
  '/admin/rls-tests': typeof AuthenticatedAdminRlsTestsRoute
  '/dashboard/adviseur': typeof AuthenticatedDashboardAdviseurRoute
  '/dashboard/kwaliteit': typeof AuthenticatedDashboardKwaliteitRoute
  '/dashboard/steekproef': typeof AuthenticatedDashboardSteekproefRoute
  '/intake/$id': typeof AuthenticatedIntakeIdRoute
  '/intake/new': typeof AuthenticatedIntakeNewRoute
  '/api/did/check': typeof ApiDidCheckRoute
  '/api/order/create': typeof ApiOrderCreateRoute
  '/api/payment/webhook': typeof ApiPaymentWebhookRoute
  '/api/provision/customer': typeof ApiProvisionCustomerRoute
  '/api/public/dev-login': typeof ApiPublicDevLoginRoute
  '/intake': typeof AuthenticatedIntakeIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRouteWithChildren
  '/_authenticated/roadmap': typeof AuthenticatedRoadmapRoute
  '/_authenticated/admin/rls-tests': typeof AuthenticatedAdminRlsTestsRoute
  '/_authenticated/dashboard/adviseur': typeof AuthenticatedDashboardAdviseurRoute
  '/_authenticated/dashboard/kwaliteit': typeof AuthenticatedDashboardKwaliteitRoute
  '/_authenticated/dashboard/steekproef': typeof AuthenticatedDashboardSteekproefRoute
  '/_authenticated/intake/$id': typeof AuthenticatedIntakeIdRoute
  '/_authenticated/intake/new': typeof AuthenticatedIntakeNewRoute
  '/api/did/check': typeof ApiDidCheckRoute
  '/api/order/create': typeof ApiOrderCreateRoute
  '/api/payment/webhook': typeof ApiPaymentWebhookRoute
  '/api/provision/customer': typeof ApiProvisionCustomerRoute
  '/api/public/dev-login': typeof ApiPublicDevLoginRoute
  '/_authenticated/intake/': typeof AuthenticatedIntakeIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/dashboard'
    | '/roadmap'
    | '/admin/rls-tests'
    | '/dashboard/adviseur'
    | '/dashboard/kwaliteit'
    | '/dashboard/steekproef'
    | '/intake/$id'
    | '/intake/new'
    | '/api/did/check'
    | '/api/order/create'
    | '/api/payment/webhook'
    | '/api/provision/customer'
    | '/api/public/dev-login'
    | '/intake/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/dashboard'
    | '/roadmap'
    | '/admin/rls-tests'
    | '/dashboard/adviseur'
    | '/dashboard/kwaliteit'
    | '/dashboard/steekproef'
    | '/intake/$id'
    | '/intake/new'
    | '/api/did/check'
    | '/api/order/create'
    | '/api/payment/webhook'
    | '/api/provision/customer'
    | '/api/public/dev-login'
    | '/intake'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/_authenticated/dashboard'
    | '/_authenticated/roadmap'
    | '/_authenticated/admin/rls-tests'
    | '/_authenticated/dashboard/adviseur'
    | '/_authenticated/dashboard/kwaliteit'
    | '/_authenticated/dashboard/steekproef'
    | '/_authenticated/intake/$id'
    | '/_authenticated/intake/new'
    | '/api/did/check'
    | '/api/order/create'
    | '/api/payment/webhook'
    | '/api/provision/customer'
    | '/api/public/dev-login'
    | '/_authenticated/intake/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
  ApiDidCheckRoute: typeof ApiDidCheckRoute
  ApiOrderCreateRoute: typeof ApiOrderCreateRoute
  ApiPaymentWebhookRoute: typeof ApiPaymentWebhookRoute
  ApiProvisionCustomerRoute: typeof ApiProvisionCustomerRoute
  ApiPublicDevLoginRoute: typeof ApiPublicDevLoginRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/roadmap': {
      id: '/_authenticated/roadmap'
      path: '/roadmap'
      fullPath: '/roadmap'
      preLoaderRoute: typeof AuthenticatedRoadmapRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/intake/': {
      id: '/_authenticated/intake/'
      path: '/intake'
      fullPath: '/intake/'
      preLoaderRoute: typeof AuthenticatedIntakeIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/api/public/dev-login': {
      id: '/api/public/dev-login'
      path: '/api/public/dev-login'
      fullPath: '/api/public/dev-login'
      preLoaderRoute: typeof ApiPublicDevLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/provision/customer': {
      id: '/api/provision/customer'
      path: '/api/provision/customer'
      fullPath: '/api/provision/customer'
      preLoaderRoute: typeof ApiProvisionCustomerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/payment/webhook': {
      id: '/api/payment/webhook'
      path: '/api/payment/webhook'
      fullPath: '/api/payment/webhook'
      preLoaderRoute: typeof ApiPaymentWebhookRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/order/create': {
      id: '/api/order/create'
      path: '/api/order/create'
      fullPath: '/api/order/create'
      preLoaderRoute: typeof ApiOrderCreateRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/did/check': {
      id: '/api/did/check'
      path: '/api/did/check'
      fullPath: '/api/did/check'
      preLoaderRoute: typeof ApiDidCheckRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/intake/new': {
      id: '/_authenticated/intake/new'
      path: '/intake/new'
      fullPath: '/intake/new'
      preLoaderRoute: typeof AuthenticatedIntakeNewRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/intake/$id': {
      id: '/_authenticated/intake/$id'
      path: '/intake/$id'
      fullPath: '/intake/$id'
      preLoaderRoute: typeof AuthenticatedIntakeIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/dashboard/steekproef': {
      id: '/_authenticated/dashboard/steekproef'
      path: '/steekproef'
      fullPath: '/dashboard/steekproef'
      preLoaderRoute: typeof AuthenticatedDashboardSteekproefRouteImport
      parentRoute: typeof AuthenticatedDashboardRoute
    }
    '/_authenticated/dashboard/kwaliteit': {
      id: '/_authenticated/dashboard/kwaliteit'
      path: '/kwaliteit'
      fullPath: '/dashboard/kwaliteit'
      preLoaderRoute: typeof AuthenticatedDashboardKwaliteitRouteImport
      parentRoute: typeof AuthenticatedDashboardRoute
    }
    '/_authenticated/dashboard/adviseur': {
      id: '/_authenticated/dashboard/adviseur'
      path: '/adviseur'
      fullPath: '/dashboard/adviseur'
      preLoaderRoute: typeof AuthenticatedDashboardAdviseurRouteImport
      parentRoute: typeof AuthenticatedDashboardRoute
    }
    '/_authenticated/admin/rls-tests': {
      id: '/_authenticated/admin/rls-tests'
      path: '/admin/rls-tests'
      fullPath: '/admin/rls-tests'
      preLoaderRoute: typeof AuthenticatedAdminRlsTestsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
  }
}

interface AuthenticatedDashboardRouteChildren {
  AuthenticatedDashboardAdviseurRoute: typeof AuthenticatedDashboardAdviseurRoute
  AuthenticatedDashboardKwaliteitRoute: typeof AuthenticatedDashboardKwaliteitRoute
  AuthenticatedDashboardSteekproefRoute: typeof AuthenticatedDashboardSteekproefRoute
}

const AuthenticatedDashboardRouteChildren: AuthenticatedDashboardRouteChildren =
  {
    AuthenticatedDashboardAdviseurRoute: AuthenticatedDashboardAdviseurRoute,
    AuthenticatedDashboardKwaliteitRoute: AuthenticatedDashboardKwaliteitRoute,
    AuthenticatedDashboardSteekproefRoute:
      AuthenticatedDashboardSteekproefRoute,
  }

const AuthenticatedDashboardRouteWithChildren =
  AuthenticatedDashboardRoute._addFileChildren(
    AuthenticatedDashboardRouteChildren,
  )

interface AuthenticatedRouteRouteChildren {
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRouteWithChildren
  AuthenticatedRoadmapRoute: typeof AuthenticatedRoadmapRoute
  AuthenticatedAdminRlsTestsRoute: typeof AuthenticatedAdminRlsTestsRoute
  AuthenticatedIntakeIdRoute: typeof AuthenticatedIntakeIdRoute
  AuthenticatedIntakeNewRoute: typeof AuthenticatedIntakeNewRoute
  AuthenticatedIntakeIndexRoute: typeof AuthenticatedIntakeIndexRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedDashboardRoute: AuthenticatedDashboardRouteWithChildren,
  AuthenticatedRoadmapRoute: AuthenticatedRoadmapRoute,
  AuthenticatedAdminRlsTestsRoute: AuthenticatedAdminRlsTestsRoute,
  AuthenticatedIntakeIdRoute: AuthenticatedIntakeIdRoute,
  AuthenticatedIntakeNewRoute: AuthenticatedIntakeNewRoute,
  AuthenticatedIntakeIndexRoute: AuthenticatedIntakeIndexRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
  ApiDidCheckRoute: ApiDidCheckRoute,
  ApiOrderCreateRoute: ApiOrderCreateRoute,
  ApiPaymentWebhookRoute: ApiPaymentWebhookRoute,
  ApiProvisionCustomerRoute: ApiProvisionCustomerRoute,
  ApiPublicDevLoginRoute: ApiPublicDevLoginRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
